language: shell 
os: windows
install:
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
  - choco install nodejs-lts;
env:
  - PATH="$PATH;C:\Program Files\nodejs"
script:
  - powershell "./scripts/verifyDocs.ps1"
  - powershell "./scripts/lintNodejsCodeSamples.ps1"
