apiVersion: v1
kind: Secret
metadata:
  name: ravendb-license
  namespace: default
  labels:
    app: ravendb
type: Opaque
data:
  license.json: <base64-value-of-license-file>
---
apiVersion: v1
kind: Secret
metadata:
  name: ravendb-ssl
  namespace: default
  labels:
    app: ravendb
type: Opaque
data:
  ssl: <base64-value-of-certificate-file>
